# Generated by Django 5.2 on 2025-04-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Mood Name')),
                ('emoji', models.CharField(blank=True, max_length=10, null=True, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Mood',
                'verbose_name_plural': 'Moods',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Song Title')),
                ('artist', models.CharField(max_length=200, verbose_name='Artist')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Review')),
                ('url', models.URLField(verbose_name='Song URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='moodecore.mood', verbose_name='Mood')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('selected_mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='moodecore.mood', verbose_name='Mood')),
            ],
            options={
                'verbose_name': 'User Input',
                'verbose_name_plural': 'User Inputs',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(verbose_name='Liked')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodecore.song', verbose_name='Song')),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodecore.userinput', verbose_name='User Input')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
